package pe.edu.unasam.activos.common.enums;

public enum TipoUnidad {
    ALMACENAMIENTO, FRECUENCIA, MEMORIA, ENERGIA, VELOCIDAD, LONGITUD, PESO, RESOLUCION, TEMPERATURA, TIEMPO,
    PROCESAMIENTO, RACK, RED, PORCENTAJE, CANTIDAD, OTRO
}
