package pe.edu.unasam.activos.common.enums;

public enum UsoApi {
    AUTENTICACION, SESIONES, VALIDACION, PRINCIPAL,NOTIFICACIONES, REPORTES, ALMACENAMIENTO, PAGOS, SEGURIDAD, SMS,
    INTERNO, EXTERNO, INTEGRACION, MICROSERVICIO
}
